import Head from 'next/head'

import { TextShowcase } from '@/components/text'
import { ButtonShowcase } from '@/components/button'

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<TextShowcase />
				<ButtonShowcase />
			</main>
		</>
	)
}